export const PRODUCT_DATA_REQUEST = 'PRODUCT_DATA_REQUEST';
export const PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS';
export const PRODUCT_DATA_FAIL = 'PRODUCT_DATA_FAIL';

export const EDIT_CART = 'EDIT_CART';